"""add_admin_models

Revision ID: 4b07eeeb055d
Revises: ca4ef976793c
Create Date: 2026-06-04 11:36:45.291760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b07eeeb055d'
down_revision: Union[str, Sequence[str], None] = 'ca4ef976793c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.Enum('super_admin', 'admin', 'support', name='adminrole'), nullable=False),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.create_table('banner_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hero_title', sa.String(length=200), nullable=False),
    sa.Column('hero_description', sa.String(length=500), nullable=False),
    sa.Column('hero_image_src', sa.String(length=500), nullable=False),
    sa.Column('hero_variant', sa.String(length=20), nullable=False),
    sa.Column('hero_active', sa.Boolean(), nullable=False),
    sa.Column('announcement_text', sa.String(length=160), nullable=False),
    sa.Column('announcement_link_label', sa.String(length=60), nullable=True),
    sa.Column('announcement_link_href', sa.String(length=200), nullable=True),
    sa.Column('announcement_style', sa.String(length=20), nullable=False),
    sa.Column('announcement_active', sa.Boolean(), nullable=False),
    sa.Column('announcement_dismissible', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platform_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('commission_rate', sa.Float(), nullable=False),
    sa.Column('withdrawal_fee', sa.Float(), nullable=False),
    sa.Column('support_email', sa.String(length=254), nullable=False),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enquiry_threads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('assigned_admin_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_admin_id'], ['admin_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verification_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id_document_key', sa.String(length=500), nullable=False),
    sa.Column('selfie_key', sa.String(length=500), nullable=False),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_requests_vendor_id'), 'verification_requests', ['vendor_id'], unique=False)
    op.create_table('escrow_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('admin_id', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escrow_logs_order_id'), 'escrow_logs', ['order_id'], unique=False)
    op.create_table('thread_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('sender_id', sa.String(), nullable=False),
    sa.Column('sender_type', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('is_internal_note', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['enquiry_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('disputes', sa.Column('priority', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('is_flagged', sa.Boolean(), nullable=False))
    op.add_column('orders', sa.Column('flag_reason', sa.String(), nullable=True))
    op.add_column('payout_records', sa.Column('reject_reason', sa.String(), nullable=True))
    op.add_column('payout_records', sa.Column('hold_note', sa.String(), nullable=True))
    op.add_column('products', sa.Column('is_flagged', sa.Boolean(), nullable=False))
    op.add_column('products', sa.Column('flag_reason', sa.String(), nullable=True))
    op.add_column('products', sa.Column('is_removed', sa.Boolean(), nullable=False))
    op.add_column('products', sa.Column('remove_reason', sa.String(), nullable=True))
    op.add_column('products', sa.Column('is_featured', sa.Boolean(), nullable=False))
    op.add_column('shops', sa.Column('status', sa.String(), nullable=False))
    op.add_column('shops', sa.Column('verified', sa.Boolean(), nullable=False))
    op.add_column('shops', sa.Column('featured', sa.Boolean(), nullable=False))
    op.add_column('shops', sa.Column('gmv', sa.Float(), nullable=False))
    op.add_column('shops', sa.Column('orders_count', sa.Integer(), nullable=False))
    op.add_column('shops', sa.Column('products_count', sa.Integer(), nullable=False))
    op.add_column('shops', sa.Column('rating', sa.Float(), nullable=False))
    op.add_column('shops', sa.Column('pending_balance', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('is_banned', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('ban_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ban_reason')
    op.drop_column('users', 'is_banned')
    op.drop_column('shops', 'pending_balance')
    op.drop_column('shops', 'rating')
    op.drop_column('shops', 'products_count')
    op.drop_column('shops', 'orders_count')
    op.drop_column('shops', 'gmv')
    op.drop_column('shops', 'featured')
    op.drop_column('shops', 'verified')
    op.drop_column('shops', 'status')
    op.drop_column('products', 'is_featured')
    op.drop_column('products', 'remove_reason')
    op.drop_column('products', 'is_removed')
    op.drop_column('products', 'flag_reason')
    op.drop_column('products', 'is_flagged')
    op.drop_column('payout_records', 'hold_note')
    op.drop_column('payout_records', 'reject_reason')
    op.drop_column('orders', 'flag_reason')
    op.drop_column('orders', 'is_flagged')
    op.drop_column('disputes', 'priority')
    op.drop_table('thread_messages')
    op.drop_index(op.f('ix_escrow_logs_order_id'), table_name='escrow_logs')
    op.drop_table('escrow_logs')
    op.drop_index(op.f('ix_verification_requests_vendor_id'), table_name='verification_requests')
    op.drop_table('verification_requests')
    op.drop_table('enquiry_threads')
    op.drop_table('platform_settings')
    op.drop_table('banner_settings')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
